### ISSUE TITLE
Failed to load a library on start

### ISSUE THREAD

**Issue by bpringe** [oakes/play-cljc#19]
I'm on MacOS. I created a project with `clj -Sdeps "{:deps {leiningen/leiningen {:mvn/version \""2.9.0\""}}}" -M -m leiningen.core.main new play-cljc <project-name>`. When I run `clj -M:dev` in the project directory, I get:

```text
2022-06-17 23:15:08.361:INFO::main: Logging initialized @1766ms to org.eclipse.jetty.util.log.StdErrLog
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Execution error (UnsatisfiedLinkError) at org.lwjgl.system.Library/loadSystem (Library.java:162).
Failed to locate library: liblwjgl.dylib
```

`java -version` output (in case it helps):

```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.15+0, mixed mode)
```

**Comment by bpringe** [comment]
I actually found this question by you, @oakes, while searching for info on this issue: https://github.com/LWJGL/lwjgl3/issues/449. I don't know if that's related though..

**Comment by oakes** [comment]
Are you on an ARM-based mac? Maybe lwjgl needs to be updated to support it. In the meantime, i made a change so the dev command doesn't try to load the lwjgl stuff. In `dev.clj` i made it so the `require`s are inside the methods and i use `resolve` to get the vars, which will delay when they are loaded:

```clojure
(defmethod task nil
  [_]
  (require '[figwheel.main :as figwheel])
  ((resolve 'figwheel/-main) "--build" "dev"))

(defmethod task "native"
  [_]
  (require '[hello-world.start-dev])
  ((resolve 'hello-world.start-dev/start)))
```

I deployed a new template with this change so if you create a new project it should now look like this.

**Comment by bpringe** [comment]
Yes to ARM-based mac. Thanks! I'll try this out when I get back around to it. I'll go ahead and close this, but if I have issues I'll report back. I appreciate the quick response.

**Comment by bpringe** [comment]
Running `clj -M:dev` worked with the new template, by the way. 🎉
