### ISSUE TITLE
Slow advanced-render examples

### ISSUE THREAD

**Issue by zsrail** [oakes/play-cljc#2]
I looked into those advanced-render examples which, as you mentioned in your screencast, have really low frame-rates. After doing some profiling, it looked like reflection and matrix math was using the most time. So I added some type-hints and redefined `identity-matrix`, `multiply-matrices`, and `inverse-matrix` to be calls to the mikera matrix library using the vectorz-clj implementation, and now the advanced-render examples seem pretty smooth. I also tested the old matrix math functions directly against the mikera calls, and the mikera calls are definitely much faster, especially as the size of the matrices grow. My understanding is that the speed difference is due to mikera's lower-level, highly optimized implementation, but also due to it's more sophisticated algorithms (it looks like your old definitions were using the classic algorithms you'd learn in a first linear algebra class). Also, I don't know much about graphics, but in numerical methods the common wisdom is that you can (and should) usually avoid computing matrix inverses; maybe something to look into, I don't know.

Anyways, if you don't mind taking on the extra dependencies, I could make a pull request with my changes if you'd like. If not, and you still want to roll your own, then I reckon you'll probably have to switch to some more sophisticated algorithms.

**Comment by oakes** [comment]
That would be really awesome. Does that library support clojurescript too?

**Comment by zsrail** [comment]
Mikera matrix works with clojurescript, but the vectorz-clj implementation doesn't. I'll play around with the other implementations to see how they do.

**Comment by oakes** [comment]
We could also just use reader conditionals so cljs continues using the existing functions.

**Comment by oakes** [comment]
Release 0.3.0 with the new matrix changes, so I'll close this. Thanks.
