### ISSUE TITLE
How to build/deploy to android

### ISSUE THREAD

**Issue by phunni** [oakes/play-cljc#22]
Running the desktop app seems fairly straightforward, but I can't see any docs on how to build, deploy and run the android part of the project?

I know this project is essentially dead at this point, but I just wanted to experiment with it.

**Comment by oakes** [comment]
I think you're confusing this with [play-clj](https://github.com/oakes/play-clj). This project is play-cljc which doesn't support android and is not dead.

**Comment by phunni** [comment]
Apologies you're quite right.
