### ISSUE TITLE
Update running game with code changes

### ISSUE THREAD

**Issue by kovasap** [oakes/play-cljc#4]
I'm having some issues making changes in my code and seeing them dynamically update my game (as I think they should?).  

I've set up my development environment by first running a following shell script in a terminal:

```
start.bash:
    port=47788
    clj -A:dev:linux -m nrepl.cmdline -p $port &
    sleep 4 # give nrepl time to start before we try to connect
    lein repl :connect localhost:$port
    echo "killing nrepl..."
    pkill -f clojure # not the best way to do this...
    echo "killed nrepl"
```

I use this because in my vim, the vim-fireplace plugin synchronizes nicely with lein's repl for whatever reason, where I couldn't get that effect from just the clj repl.  Then, in the repl I get from that script, I run:

```
user=> (doto 'hello-world.start-dev require in-ns)
hello-world.start-dev=> (start)
```

This boots up the game as expected.  However, when I change code in my editor and save it, I do not see a dynamic update (as I did when I was playing with the web version of this game, as opposed to the linux native, which I'm using here).  The only way I have been able to see updates is closing down my repl and restarting.  Am I missing something here?

**Comment by oakes** [comment]
After editing your file, are you doing anything to reload the code? I'm not familiar with vim fireplace but I am guessing there is a command you need to run, as opposed to figwheel which listens for file changes and reloads automatically.

**Comment by kovasap** [comment]
Yep that was it.  I needed to run :Require (keybound to cpr).  Thanks!
