### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by kovasap** [oakes/play-cljc#8]
Is there a way currently to render text?  If not, what would need to be done to make it possible?  I could try to look into it if it's not currently possible!

**Comment by oakes** [comment]
That's definitely what I will be working on next. I'm going to use the [STB](https://javadoc.lwjgl.org/org/lwjgl/stb/package-summary.html) library to do it (in particular, STBEasyFont and STBTrueType), and I'll have to figure out a way to get the equivalent behavior on the webgl side. I will most likely make a wrapper library so you don't need to use these things directly.

**Comment by oakes** [comment]
It took me a while, but I finally made the text-rendering library: [play-cljc.text](https://github.com/oakes/play-cljc.text). I made [an example project](https://github.com/oakes/play-cljc-examples/tree/master/ui-gallery) showing how to use it.

**Comment by kovasap** [comment]
Awesome!  Thanks!
